# Generated by Django 3.0.2 on 2020-02-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0003_modelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MODELNAME',
            new_name='Car',
        ),
    ]
